name: quadruped_pympc_ros2_env
channels:
- conda-forge
- nvidia
- robostack-staging
dependencies:
- pip
- python
- casadi
- numpy
- matplotlib
- jaxlib
- jax 
- meshcat-python 
- scipy==1.15.1  
- pinocchio
- adam-robotics[all]
- ros-humble-desktop
- ros-humble-plotjuggler-ros
- ros-humble-rmw-cyclonedds-cpp
- ros-humble-rosidl-generator-dds-idl
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- tqdm
- gymnasium
- pip:
  - mujoco
  - readchar
  - liecasadi

