module dls2_interface
{
  module msg
  {
    struct Imu
    {
      // header
      string frame_id;
      unsigned long sequence_id;
      double timestamp;

      // data
      double orientation[4]; //x, y, z, w
      double orientation_rpy[3];
      double orientation_covariance[9];
      double angular_velocity[3];
      double angular_velocity_covariance[9];
      double linear_acceleration[3];
      double linear_acceleration_covariance[9];
    };
  };
};