/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) centroidal_model_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s1[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[33] = {29, 1, 0, 29, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28};
static const casadi_int casadi_s4[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s5[59] = {54, 20, 0, 2, 4, 6, 8, 9, 11, 13, 15, 17, 18, 20, 22, 24, 26, 27, 29, 31, 33, 35, 36, 12, 14, 13, 14, 13, 14, 12, 14, 14, 15, 17, 16, 17, 16, 17, 15, 17, 17, 18, 20, 19, 20, 19, 20, 18, 20, 20, 21, 23, 22, 23, 22, 23, 21, 23, 23};
static const casadi_int casadi_s6[3] = {20, 0, 0};

/* centroidal_model_constr_h_fun_jac_uxt_zt:(i0[30],i1[24],i2[],i3[29])->(o0[20],o1[54x20,36nz],o2[20x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[1]? arg[1][12] : 0;
  a1=arg[3]? arg[3][4] : 0;
  a2=arg[1]? arg[1][14] : 0;
  a3=(a1*a2);
  a3=(a0-a3);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[1]? arg[1][13] : 0;
  a4=(a1*a2);
  a4=(a3-a4);
  if (res[0]!=0) res[0][1]=a4;
  a4=(a1*a2);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=(a1*a2);
  a0=(a0+a3);
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a2;
  a2=arg[1]? arg[1][15] : 0;
  a0=arg[1]? arg[1][17] : 0;
  a3=(a1*a0);
  a3=(a2-a3);
  if (res[0]!=0) res[0][5]=a3;
  a3=arg[1]? arg[1][16] : 0;
  a4=(a1*a0);
  a4=(a3-a4);
  if (res[0]!=0) res[0][6]=a4;
  a4=(a1*a0);
  a3=(a3+a4);
  if (res[0]!=0) res[0][7]=a3;
  a3=(a1*a0);
  a2=(a2+a3);
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][18] : 0;
  a2=arg[1]? arg[1][20] : 0;
  a3=(a1*a2);
  a3=(a0-a3);
  if (res[0]!=0) res[0][10]=a3;
  a3=arg[1]? arg[1][19] : 0;
  a4=(a1*a2);
  a4=(a3-a4);
  if (res[0]!=0) res[0][11]=a4;
  a4=(a1*a2);
  a3=(a3+a4);
  if (res[0]!=0) res[0][12]=a3;
  a3=(a1*a2);
  a0=(a0+a3);
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a2;
  a2=arg[1]? arg[1][21] : 0;
  a0=arg[1]? arg[1][23] : 0;
  a3=(a1*a0);
  a3=(a2-a3);
  if (res[0]!=0) res[0][15]=a3;
  a3=arg[1]? arg[1][22] : 0;
  a4=(a1*a0);
  a4=(a3-a4);
  if (res[0]!=0) res[0][16]=a4;
  a4=(a1*a0);
  a3=(a3+a4);
  if (res[0]!=0) res[0][17]=a3;
  a3=(a1*a0);
  a2=(a2+a3);
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][1]=a2;
  if (res[1]!=0) res[1][2]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][3]=a2;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a1;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a1;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][10]=a2;
  if (res[1]!=0) res[1][11]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][12]=a2;
  if (res[1]!=0) res[1][13]=a0;
  if (res[1]!=0) res[1][14]=a1;
  if (res[1]!=0) res[1][15]=a0;
  if (res[1]!=0) res[1][16]=a1;
  if (res[1]!=0) res[1][17]=a0;
  if (res[1]!=0) res[1][18]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][19]=a2;
  if (res[1]!=0) res[1][20]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][21]=a2;
  if (res[1]!=0) res[1][22]=a0;
  if (res[1]!=0) res[1][23]=a1;
  if (res[1]!=0) res[1][24]=a0;
  if (res[1]!=0) res[1][25]=a1;
  if (res[1]!=0) res[1][26]=a0;
  if (res[1]!=0) res[1][27]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][28]=a2;
  if (res[1]!=0) res[1][29]=a0;
  a2=(-a1);
  if (res[1]!=0) res[1][30]=a2;
  if (res[1]!=0) res[1][31]=a0;
  if (res[1]!=0) res[1][32]=a1;
  if (res[1]!=0) res[1][33]=a0;
  if (res[1]!=0) res[1][34]=a1;
  if (res[1]!=0) res[1][35]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int centroidal_model_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int centroidal_model_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int centroidal_model_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centroidal_model_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int centroidal_model_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centroidal_model_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void centroidal_model_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void centroidal_model_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int centroidal_model_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int centroidal_model_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real centroidal_model_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centroidal_model_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centroidal_model_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centroidal_model_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centroidal_model_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int centroidal_model_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
